from sqlalchemy import BigInteger

from app.db.models import AnalyticsEvent, Application, AdminUser, ApplicationDraft, ApplicationDuplicateIndex, BlockedTelegramUser, CalculatorLead, ClientActionLog, Consent, ContentText, DataDeletionRequest, NotificationDeduplication, NotificationLog, NotificationPreference, NotificationRule, NotificationTemplate, Operator, OperatorActionLog, OperatorInternalComment, OperatorTicket, OperatorTicketTransfer, ReminderTask, RepeatApplicationDraft, Tariff, TariffChangeLog, TelegramBitrixLink


def assert_bigint_column(model, column_name: str) -> None:
    assert isinstance(model.__table__.columns[column_name].type, BigInteger)


def test_telegram_and_operator_ids_use_bigint():
    assert_bigint_column(Application, "telegram_user_id")
    assert_bigint_column(OperatorTicket, "telegram_user_id")
    assert_bigint_column(OperatorTicket, "telegram_chat_id")
    assert_bigint_column(OperatorTicket, "bitrix_deal_id")
    assert_bigint_column(OperatorTicket, "bitrix_contact_id")
    assert_bigint_column(OperatorTicket, "operator_id")
    assert_bigint_column(OperatorTicket, "assigned_by_operator_id")
    assert_bigint_column(OperatorTicket, "previous_operator_id")
    assert_bigint_column(OperatorTicketTransfer, "from_operator_id")
    assert_bigint_column(OperatorTicketTransfer, "to_operator_id")
    assert_bigint_column(OperatorTicketTransfer, "transferred_by_operator_id")
    assert_bigint_column(OperatorInternalComment, "bitrix_deal_id")
    assert_bigint_column(OperatorInternalComment, "operator_id")
    assert_bigint_column(OperatorActionLog, "operator_id")
    assert_bigint_column(AnalyticsEvent, "telegram_user_id")
    assert_bigint_column(TelegramBitrixLink, "telegram_user_id")
    assert_bigint_column(TelegramBitrixLink, "telegram_chat_id")
    assert_bigint_column(TelegramBitrixLink, "bitrix_contact_id")
    assert_bigint_column(ClientActionLog, "telegram_user_id")
    assert_bigint_column(ClientActionLog, "bitrix_deal_id")
    assert_bigint_column(RepeatApplicationDraft, "telegram_user_id")
    assert_bigint_column(RepeatApplicationDraft, "old_bitrix_deal_id")
    assert_bigint_column(ApplicationDuplicateIndex, "application_id")
    assert_bigint_column(ApplicationDuplicateIndex, "telegram_user_id")
    assert_bigint_column(ApplicationDuplicateIndex, "bitrix_deal_id")
    assert_bigint_column(Consent, "application_id")
    assert_bigint_column(Consent, "telegram_user_id")
    assert_bigint_column(DataDeletionRequest, "telegram_user_id")
    assert_bigint_column(DataDeletionRequest, "bitrix_contact_id")
    assert_bigint_column(BlockedTelegramUser, "telegram_user_id")
    assert_bigint_column(BlockedTelegramUser, "blocked_by_operator_id")
    assert_bigint_column(Operator, "telegram_user_id")
    assert_bigint_column(TariffChangeLog, "tariff_id")
    assert_bigint_column(TariffChangeLog, "admin_user_id")
    assert_bigint_column(AdminUser, "id")
    assert_bigint_column(Tariff, "id")
    assert_bigint_column(ContentText, "id")
    assert_bigint_column(NotificationTemplate, "id")
    assert_bigint_column(NotificationRule, "id")
    assert_bigint_column(NotificationLog, "id")
    assert_bigint_column(NotificationDeduplication, "id")

    assert_bigint_column(ReminderTask, "telegram_user_id")
    assert_bigint_column(ReminderTask, "telegram_chat_id")
    assert_bigint_column(ReminderTask, "bitrix_deal_id")
    assert_bigint_column(CalculatorLead, "telegram_user_id")
    assert_bigint_column(CalculatorLead, "telegram_chat_id")
    assert_bigint_column(ApplicationDraft, "telegram_user_id")
    assert_bigint_column(ApplicationDraft, "telegram_chat_id")
    assert_bigint_column(NotificationPreference, "telegram_user_id")
